site_name: awadih
site_url: https://awadih.github.io/
site_author: A. Wadih
site_description: 'A personal blog with interests'
repo_url: 'https://github.com/awadih/awadih.github.io'
copyright: ''
theme:
  name: readthedocs
  colorscheme: github
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  favicon: img/favicon.ico
nav:
  - 'About Me':
      - 'bio': 'index.md'
  - 'Projects':
      - 'dx-Dash': 'projects/dx_dash.md'
      - 'Energy-project': 'projects/greedy_algo.md'
  - 'Interests':
      - 'Volunteering': 'interests/volunteering.md'
      - 'Leisure Activities': 'interests/leisure.md'
  - 'Contact':
      - 'Research Profile': 'contact/research_profile.md'
      - 'Social media': 'contact/social_media.md'
      - 'Email': 'contact/email.md'
